require:
  - rubocop-rails
  - rubocop-performance
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 25
Metrics/BlockNesting:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/LineLength:
  Max: 180
Rails/DynamicFindBy:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
