require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/RedundantRegexpCharacterClass:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 30
Layout/LineLength:
  Max: 200
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Bundler/OrderedGems:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
RSpec/FactoryBot/CreateList:
  EnforcedStyle: n_times

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
