#!/usr/bin/env ruby

# frozen_string_literal: true

require 'rubocop'

ADDED_OR_MODIFIED = /A|AM|^M/.freeze

changes = `git status --porcelain`.split(/\n/)

changes.select! do |file_name_with_status|
  file_name_with_status =~ ADDED_OR_MODIFIED
end
changed_files = changes.map do |file_name_with_status|
  file_name_with_status.split(' ')[1]
end
changed_files.select! do |file_name|
  File.extname(file_name) == '.rb' &&
    !file_name.start_with?('bin/') &&
    !file_name.start_with?('db/schema')
end

system("rubocop #{changed_files.join(' ')}") unless changed_files.empty?

exit $CHILD_STATUS.to_s[-1].to_i
