#!/usr/bin/env ruby

# frozen_string_literal: true

require 'rubocop'

ADDED_OR_MODIFIED = /A|AM|^M/.freeze

changes = `git status --porcelain`.split(/\n/)
changes.select! { |file_name_with_status| file_name_with_status =~ ADDED_OR_MODIFIED }
changed_files = changes.map { |file_name_with_status| file_name_with_status.split[1] }

ruby_files = changed_files.select { |file_name| File.extname(file_name) == '.rb' }
system("rubocop --force-exclusion #{ruby_files.join(' ')}") unless ruby_files.empty?

exit $CHILD_STATUS.to_s[-1].to_i
